# Generated by Django 4.1.4 on 2022-12-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='file')),
                ('geo_location', models.CharField(blank=True, max_length=255, verbose_name='Геолокация')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('names_of_people', models.TextField(blank=True)),
            ],
        ),
    ]
