# Generated by Django 3.2 on 2022-12-09 12:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20221209_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='date_load',
            field=models.DateField(auto_created=True, default=django.utils.timezone.now),
        ),
    ]
