# Generated by Django 3.2 on 2022-12-09 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0003_alter_photo_date_load'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='date_load',
            field=models.DateField(auto_created=True),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='names_of_people',
        ),
        migrations.AddField(
            model_name='photo',
            name='names_of_people',
            field=models.ManyToManyField(to='photo.UserName'),
        ),
    ]
